owner: ultracold273
repo: blog

site:
  author: Lingxiao
  title: Lingxiao
  description: Lingxiao 的个人博客
  url: https://www.lxwei.me
  since: 2015
  icon: /static/images/icon.png
  rss: /atom.xml
  about: 1

social:
  twitter: ultracold273

theme:
  color: "#DB1105"

menu:
  - name: 归档
    url: /archives
  - name: 关于我
    url: /about
